// Package main реализует генератор методов Reset() для Go-структур.
//
// # Использование
//
//	go run ./cmd/reset [директория]
//
// Если директория не указана, сканируется текущий рабочий каталог.
//
// # Алгоритм
//
//  1. Рекурсивно сканирует все пакеты начиная с указанной директории.
//  2. В каждом пакете ищет структуры с комментарием // generate:reset.
//  3. Для каждой такой структуры генерирует метод Reset().
//  4. Все методы одного пакета записываются в файл reset.gen.go того же пакета.
//
// # Правила генерации Reset()
//
//   - Примитивные поля (int, string, bool и т.д.) сбрасываются к нулевому значению.
//   - Срезы обрезаются до нулевой длины без обнуления: s = s[:0].
//   - Мапы очищаются встроенной функцией clear(m).
//   - Указатели на примитивы: если не nil, значение обнуляется.
//   - Указатели на именованные типы: если не nil и тип реализует Reset(),
//     метод вызывается.
//   - Именованные типы (не указатели): если реализуют Reset(), метод вызывается.
//   - Каналы, функции, интерфейсы: устанавливаются в nil.
//   - Массивы фиксированного размера: сбрасываются составным литералом T{}.
//   - Встроенные (anonymous) поля пропускаются.
//
// # Пример структуры и сгенерированного метода
//
//	// generate:reset
//	type Cache struct {
//	    size  int
//	    name  string
//	    items []string
//	    index map[string]int
//	    next  *Cache
//	}
//
// Сгенерированный Reset():
//
//	func (c *Cache) Reset() {
//	    if c == nil { return }
//	    c.size = 0
//	    c.name = ""
//	    c.items = c.items[:0]
//	    clear(c.index)
//	    if c.next != nil {
//	        if resetter, ok := any(c.next).(interface{ Reset() }); ok {
//	            resetter.Reset()
//	        }
//	    }
//	}
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path/filepath"
	"strings"
	"text/template"
)

const resetComment = "generate:reset"
const genFileName = "reset.gen.go"

var fileTmpl = template.Must(template.New("file").Parse(
	"// Code generated by cmd/reset. DO NOT EDIT.\n\npackage {{.}}\n\n",
))

var methodTmpl = template.Must(template.New("method").Funcs(template.FuncMap{
	"indent": indentLines,
}).Parse(
	"func ({{.Recv}} *{{.Name}}) Reset() {\n" +
		"\tif {{.Recv}} == nil {\n\t\treturn\n\t}\n" +
		"{{.Body | indent}}}\n\n",
))

// indentLines добавляет один отступ (\t) к каждой непустой строке.
func indentLines(s string) string {
	var b strings.Builder
	for _, line := range strings.Split(s, "\n") {
		if line != "" {
			b.WriteString("\t" + line + "\n")
		}
	}
	return b.String()
}

func main() {
	root := "."
	if len(os.Args) > 1 {
		root = os.Args[1]
	}
	if err := run(root); err != nil {
		fmt.Fprintln(os.Stderr, err)
	}
}

// structMeta содержит данные о структуре, для которой нужно сгенерировать Reset().
type structMeta struct {
	name   string
	fields []*ast.Field
}

func run(root string) error {
	// Группируем .go-файлы по директориям.
	dirFiles := map[string][]string{}
	err := filepath.Walk(root, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		if info.IsDir() {
			name := info.Name()
			// Пропускаем скрытые директории (кроме "." — корня), vendor и testdata.
			if name == "vendor" || name == "testdata" ||
				(len(name) > 1 && name[0] == '.') {
				return filepath.SkipDir
			}
			return nil
		}
		if !strings.HasSuffix(path, ".go") ||
			strings.HasSuffix(path, "_test.go") ||
			strings.HasSuffix(path, ".gen.go") {
			return nil
		}
		dir := filepath.Dir(path)
		dirFiles[dir] = append(dirFiles[dir], path)
		return nil
	})
	if err != nil {
		return err
	}

	// Обрабатываем каждый пакет.
	for dir, files := range dirFiles {
		if err := processPackage(dir, files); err != nil {
			return err
		}
	}
	return nil
}

// processPackage разбирает все файлы пакета, находит аннотированные структуры
// и генерирует reset.gen.go при наличии таковых.
func processPackage(dir string, files []string) error {
	fset := token.NewFileSet()
	var pkgName string
	var structs []structMeta

	for _, path := range files {
		f, err := parser.ParseFile(fset, path, nil, parser.ParseComments)
		if err != nil {
			fmt.Fprintf(os.Stderr, "warn: parse %s: %v\n", path, err)
			continue
		}
		if pkgName == "" {
			pkgName = f.Name.Name
		}
		structs = append(structs, findAnnotatedStructs(f)...)
	}

	if len(structs) == 0 {
		return nil
	}
	return writeGenFile(dir, pkgName, fset, structs)
}

// findAnnotatedStructs возвращает все структуры файла с комментарием // generate:reset.
func findAnnotatedStructs(f *ast.File) []structMeta {
	var result []structMeta
	for _, decl := range f.Decls {
		gd, ok := decl.(*ast.GenDecl)
		if !ok || gd.Tok != token.TYPE {
			continue
		}
		for _, spec := range gd.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			if !hasResetComment(ts.Doc) && !hasResetComment(gd.Doc) {
				continue
			}
			result = append(result, structMeta{
				name:   ts.Name.Name,
				fields: st.Fields.List,
			})
		}
	}
	return result
}

// hasResetComment проверяет наличие // generate:reset в группе комментариев.
func hasResetComment(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		text := strings.TrimSpace(strings.TrimPrefix(c.Text, "//"))
		if text == resetComment {
			return true
		}
	}
	return false
}

// writeGenFile форматирует и записывает reset.gen.go для пакета.
func writeGenFile(dir, pkgName string, fset *token.FileSet, structs []structMeta) error {
	var buf bytes.Buffer
	if err := fileTmpl.Execute(&buf, pkgName); err != nil {
		return fmt.Errorf("template file header: %w", err)
	}
	for _, s := range structs {
		if err := writeResetMethod(&buf, s, fset); err != nil {
			return err
		}
	}
	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("format %s/%s: %w\n%s", dir, genFileName, err, buf.Bytes())
	}
	outPath := filepath.Join(dir, genFileName)
	fmt.Printf("generated: %s\n", outPath)
	return os.WriteFile(outPath, src, 0644)
}

// writeResetMethod записывает в buf метод Reset() для одной структуры через text/template.
func writeResetMethod(buf *bytes.Buffer, s structMeta, fset *token.FileSet) error {
	recv := strings.ToLower(string([]rune(s.name)[0]))

	var body strings.Builder
	for _, field := range s.fields {
		if len(field.Names) == 0 {
			// Встроенное (anonymous) поле — пропускаем.
			continue
		}
		for _, name := range field.Names {
			if name.Name == "_" {
				continue
			}
			fp := recv + "." + name.Name
			body.WriteString(resetCode(fp, field.Type, fset))
		}
	}

	return methodTmpl.Execute(buf, struct {
		Recv string
		Name string
		Body string
	}{
		Recv: recv,
		Name: s.name,
		Body: body.String(),
	})
}

// resetCode возвращает строку кода сброса поля fp с типом expr.
func resetCode(fp string, expr ast.Expr, fset *token.FileSet) string {
	switch t := expr.(type) {
	case *ast.Ident:
		// Предопределённые интерфейсные типы → nil.
		if t.Name == "error" || t.Name == "any" {
			return fmt.Sprintf("%s = nil\n", fp)
		}
		// Примитивы → нулевое значение.
		if zv := primitiveZero(t.Name); zv != "" {
			return fmt.Sprintf("%s = %s\n", fp, zv)
		}
		// Именованный тип — вызвать Reset(), если есть.
		return fmt.Sprintf(
			"if resetter, ok := any(&%s).(interface{ Reset() }); ok {\n\tresetter.Reset()\n}\n",
			fp,
		)

	case *ast.StarExpr:
		return resetPtrCode(fp, t.X, fset)

	case *ast.ArrayType:
		if t.Len == nil {
			// Срез: обрезаем без обнуления.
			return fmt.Sprintf("%s = %s[:0]\n", fp, fp)
		}
		// Массив фиксированного размера: сброс составным литералом.
		return fmt.Sprintf("%s = %s{}\n", fp, astStr(fset, expr))

	case *ast.MapType:
		return fmt.Sprintf("clear(%s)\n", fp)

	case *ast.ChanType, *ast.FuncType, *ast.InterfaceType:
		return fmt.Sprintf("%s = nil\n", fp)

	case *ast.SelectorExpr:
		// Квалифицированный тип pkg.Type — вызвать Reset(), если есть.
		return fmt.Sprintf(
			"if resetter, ok := any(&%s).(interface{ Reset() }); ok {\n\tresetter.Reset()\n}\n",
			fp,
		)

	default:
		return ""
	}
}

// resetPtrCode генерирует сброс для указательного поля.
func resetPtrCode(fp string, inner ast.Expr, fset *token.FileSet) string {
	switch t := inner.(type) {
	case *ast.Ident:
		if zv := primitiveZero(t.Name); zv != "" {
			// *primitive → обнуляем значение по указателю.
			return fmt.Sprintf("if %s != nil {\n\t*%s = %s\n}\n", fp, fp, zv)
		}
		// *NamedType → вызвать Reset(), если есть.
		return fmt.Sprintf(
			"if %s != nil {\n\tif resetter, ok := any(%s).(interface{ Reset() }); ok {\n\t\tresetter.Reset()\n\t}\n}\n",
			fp, fp,
		)

	case *ast.SelectorExpr:
		// *pkg.Type
		return fmt.Sprintf(
			"if %s != nil {\n\tif resetter, ok := any(%s).(interface{ Reset() }); ok {\n\t\tresetter.Reset()\n\t}\n}\n",
			fp, fp,
		)

	default:
		// *[]T, **T и т.п. — сбрасываем через нулевое значение.
		return fmt.Sprintf("if %s != nil {\n\t*%s = *new(%s)\n}\n", fp, fp, astStr(fset, inner))
	}
}

// primitiveZero возвращает нулевой литерал для примитивного типа или "".
func primitiveZero(typeName string) string {
	switch typeName {
	case "bool":
		return "false"
	case "string":
		return `""`
	case "int", "int8", "int16", "int32", "int64",
		"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
		"float32", "float64", "complex64", "complex128",
		"byte", "rune":
		return "0"
	}
	return ""
}

// astStr преобразует AST-узел в строку через go/printer.
func astStr(fset *token.FileSet, node any) string {
	var buf bytes.Buffer
	if err := printer.Fprint(&buf, fset, node); err != nil {
		return fmt.Sprintf("/* error: %v */", err)
	}
	return buf.String()
}
